spring:
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_time?rewriteBatchedStatements=true
    username: user
    password: user123

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        order_inserts: true
        order_updates: true
        batch_versioned_date: true
        jdbc:
          batch_size: 500
      dialect: org.hibernate.dialect.MySQL8Dialect

    open-in-view: false
    defer-datasource-initialization: true
