# 유저 테스트

### 1. 일반 회원가입 API
POST {{localhost}}/signup
Content-Type: application/json

{
  "name" : "정인호",
  "nickname" : "이노",
  "email" : "enolj@gmail.com",
  "birthday" : "1996-02-27",
  "password" : "1234",
  "profileImage" : "https://29954ac4d443cb1e3d6c.jpg",
  "gender" : 0
}

### 2. 일반 로그인 API
POST {{localhost}}/login
Content-Type: application/json

{
  "email" : "enolj@gmail.com",
  "password" : "1234"
}

### 3. 회원 조회 API
GET {{localhost}}/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb2RlUXVhcnRldHRlIiwic3ViIjoiZW5vbGpAZ21haWwuY29tIiwicm9sZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2OTA1MjM3OTV9.fVrBt-qGhGWVbf1_LEj5Kk-BgxgTJXcjxvM_MkbJDAw

### 4. 회원 정보 수정 API
PATCH {{localhost}}/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb2RlUXVhcnRldHRlIiwic3ViIjoiZW5vbGpAZ21haWwuY29tIiwicm9sZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2OTA1MzQ1NTB9.kEf48_OZha_muRLPLXKoWIlUfQ57vK1TotW34A-MODc

{
  "password" : "1234",
  "newPassword" : "5678",
  "nickname" : "enolj",
  "name" : "이노"
}

### 5. 회원 삭제 API
DELETE {{localhost}}/user?id=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb2RlUXVhcnRldHRlIiwic3ViIjoiZW5vbGpAZ21haWwuY29tIiwicm9sZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2OTA1MzUzODN9.ujGPf1IjaHee3GRcLCsRRURyx4PBVLqX7wgwZ8KENwk

{
  "password" : "1234"
}
