# 유저 테스트

### 1. 일반 회원가입 API
POST {{localhost}}/signup
Content-Type: application/json

{
  "name" : "정인호",
  "nickname" : "이노",
  "email" : "enolj@gmail.com",
  "birthday" : "1991-11-09",
  "password" : "1234",
  "profileImage" : "https://www.challansdeparis.co.kr/web/product/big/202204/4bb42db09fd829954ac4d443cb1e3d6c.jpg",
  "gender" : 0
}

