# 유저 테스트

### 1. 일반 회원가입 API
POST {{localhost}}/signup
Content-Type: application/json

{
  "name" : "정인호",
  "nickname" : "이노",
  "email" : "enolj@gmail.com",
  "birthday" : "1991-11-09",
  "password" : "1234",
  "profileImage" : "https://29954ac4d443cb1e3d6c.jpg",
  "gender" : 0
}

### 2. 일반 로그인 API
POST {{localhost}}/login
Content-Type: application/json

{
  "email" : "enolj@gmail.com",
  "password" : "1234"
}
