= MyTime
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[OVERVIEW]]
== Overview

[[OVERVIEW-HOST]]
===  HOST

|===
| 환경 | HOST
| DOCKER
| http://localhost/

| LOCAL
| http://localhost:8080/
|===

[[OVERVIEW-RESPONSE-CODE]]
=== RESPONSE CODE

|===
| CODE | MESSAGE | DESCRIPTION
| `200`
| OK
| 성공

| `400`
| Bad Request
| 잘못된 요청

| `404`
| Not Found
| 존재하지 않는 요청 리소스

| `500`
| Internal Server Error
| 서버 에러

|===
[[Color-API]]
== Color API

operation::search-color[snippets='curl-request,http-request,request-headers,request-parameters,http-response,response-body,response-fields,response-headers']


[[Schdule-API]]
== Schedule API

[[Schdule-API-FIND]]
=== 스케줄 조회

operation::search-schedule[snippets='curl-request,http-request,request-headers,request-parameters,http-response,response-body,response-fields,response-headers']

[[Schdule-API-ADD]]
=== 스케줄 등록

operation::add-schedule[snippets='curl-request,http-request,request-headers,request-fields,http-response,response-body,response-fields,response-headers']

[[Schdule-API-UPDATE]]
=== 스케줄 수정

operation::update-schedule[snippets='curl-request,http-request,request-headers,path-parameters,request-fields,http-response,response-body,response-fields,response-headers']

[[Schdule-API-DELETE]]
=== 스케줄 삭제

operation::delete-schedule[snippets='curl-request,http-request,request-headers,path-parameters,http-response,response-body,response-fields,response-headers']
