[[User-API]]
== User API

[[User-API-SIGNUP]]
=== 회원가입

operation::signup-user[snippets='curl-request,http-request,request-headers,request-fields,http-response,response-headers,response-fields']

[[User-API-LOGIN]]
=== 로그인

operation::login-user[snippets='curl-request,http-request,request-headers,request-fields,http-response,response-headers,response-fields']

[[User-API-LOGOUT]]
=== 로그아웃

operation::logout-user[snippets='curl-request,http-request,request-headers,http-response,response-headers']

[[User-API-Reissue-Token]]
=== 토큰 재발급

operation::reissueToken-user[snippets='curl-request,http-request,request-headers,http-response,response-headers,response-fields']

[[User-API-FIND]]
=== 유저 정보 조회

operation::get-user[snippets='curl-request,http-request,request-headers,http-response,response-headers,response-fields']

[[User-API-UPDATE]]
=== 유저 정보 변경

operation::update-user[snippets='curl-request,http-request,request-headers,request-fields,http-response,response-headers,response-fields']

[[User-API-DELETE]]
=== 회원 탈퇴

operation::delete-user[snippets='curl-request,http-request,request-headers,request-fields,http-response,response-headers,response-fields']
